run:
  timeout: 30s
  go: '1.21'
  issues:
    exclude-dirs:
      - vendor
      - third_party
      - .git
      - api/types  # Exclude generated protobuf files
  # Add concurrency limit
  concurrency: 2
  # Add memory limit
  max-same-issues: 10

linters:
  disable-all: true
  enable:
    # Enable only essential linters
    - gofmt      # Fast, no complex analysis
    - govet      # Essential checks
    - errcheck   # Critical error checking
    - staticcheck # Important but efficient

linters-settings:
  revive:
    confidence: 0.8
  govet:
    check-shadowing: true
    fieldalignment: true
    nilfunc: true
    nilness: true
    printf: true
    structtag: true
    unreachable: true
  gofmt:
    simplify: true
  golint:
    min-confidence: 0  # Disabled, use revive instead

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
    - path: .*\.pb\.go
      linters:
        - all
    - path: api/types/.*\.pb\.go
      linters:
        - all
