run:
  timeout: 30s
  go: '1.22'
  issues:
    exclude-dirs:
      - vendor
      - third_party
      - .git
      - api/types  # Exclude generated protobuf files
  concurrency: 2
  max-same-issues: 10

linters:
  disable-all: true
  enable:
    - gofmt      # Fast, no complex analysis
    - govet      # Essential checks
    - errcheck   # Critical error checking
    - staticcheck # Important but efficient
    - shadow     # Replaces check-shadowing

linters-settings:
  govet:
    fieldalignment: true
    nilfunc: true
    nilness: true
    printf: true
    structtag: true
    unreachable: true
  gofmt:
    simplify: true
  shadow:
    strict: true

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
    - path: .*\.pb\.go
      linters:
        - all
    - path: api/types/.*\.pb\.go
      linters:
        - all
