run:
  timeout: 5m
  go: '1.22'
  issues:
    exclude-dirs:
      - vendor
      - third_party
      - .git
      - api/types  # Exclude generated protobuf files
  concurrency: 4  # Increased from 2 to improve parallel processing
  max-same-issues: 5  # Reduced from 10 to limit output
  allow-parallel-runners: true
  modules-download-mode: readonly
  tests: false
  skip-dirs-use-default: true

output:
  formats:
    - format: github-actions
  print-issued-lines: true
  print-linter-name: true
  sort-results: true
  uniq-by-line: true  # Reduce duplicate issues

linters:
  disable-all: false  # Enable selective linters
  enable:
    - govet      # Essential checks
    - errcheck   # Critical error checking
    - staticcheck # Important static analysis
    - gosimple   # Simplify code
    - gofmt      # Code formatting
    - revive     # Replacement for golint
    - unused     # Find unused code
  disable:
    - gocyclo    # Complexity checks can be resource-intensive
    - misspell   # Spelling checks can slow down linting
    - prealloc   # Performance optimization checks can be expensive
    - unconvert  # Conversion checks can be resource-heavy
    - whitespace # Redundant with gofmt

linters-settings:
  govet:
    enable-all: false
    disable:
      - shadow # Disable shadow checking in govet since it's noisy
    fieldalignment: true
    nilfunc: true
    nilness: true
    printf: true
    structtag: true
    unreachable: true
  gofmt:
    simplify: true
  staticcheck:
    checks:
      - "all"  # Enable all checks, but with performance in mind
      - "-SA1029"  # Ignore some less critical checks

issues:
  max-issues-per-linter: 5  # Reduced from 10 to limit output
  max-same-issues: 5
  exclude-files:
    - ".*\\.pb\\.go$"
    - ".*\\.mock\\.go$"
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
    - path: .*\.pb\\.go
      linters:
        - all
    - path: api/types/.*\\.pb\\.go
      linters:
        - all
