run:
  timeout: 1m
  go: '1.21'
  issues:
    exclude-dirs:
      - vendor
      - third_party
      - .git
      - api/types  # Exclude generated protobuf files

linters:
  disable-all: true
  enable:
    - revive  # Replaces deprecated golint
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - unused
    - gofmt

linters-settings:
  revive:
    confidence: 0.8
  govet:
    check-shadowing: true
    fieldalignment: true
    nilfunc: true
    nilness: true
    printf: true
    structtag: true
    unreachable: true
  gofmt:
    simplify: true
  golint:
    min-confidence: 0  # Disabled, use revive instead

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
    - path: .*\.pb\.go
      linters:
        - all
    - path: api/types/.*\.pb\.go
      linters:
        - all
