run:
  timeout: 5m
  issues:
    exclude-dirs:
      - vendor
      - third_party
      - .git

linters:
  disable-all: true
  enable:
    - revive  # Replaces deprecated golint
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - unused
    - gofmt
    - shadow

linters-settings:
  revive:
    confidence: 0.8
  govet:
    enable-all: true
  gofmt:
    simplify: true
  golint:
    min-confidence: 0  # Disabled, use revive instead
  shadow:
    # Optionally configure shadow linter
    # Add any specific shadow linter settings here

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
