run:
  timeout: 5m
  issues:
    exclude-dirs:
      - vendor
      - third_party
      - .git

linters:
  disable-all: true
  enable:
    - revive  # Replaces deprecated golint
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - unused
    - gofmt
    - shadow  # Replaces deprecated govet check-shadowing

linters-settings:
  revive:
    confidence: 0.8
  govet:
    enable-all: true
  gofmt:
    simplify: true

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec

# Explicitly disable deprecated linters
linters-settings:
  golint:
    min-confidence: 0  # Disabled, use revive instead
