version: '3.8'

services:
  postgres:
    image: postgres:13
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  migrate:
    build:
      context: .
      dockerfile: docker/Dockerfile.app
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    command: ["/scripts/postgres-migrate.sh"]

  api:
    build:
      context: .
      dockerfile: docker/Dockerfile.app
    env_file:
      - .env
    ports:
      - "8080:8080"  # REST Gateway
      - "9008:9008"  # gRPC Server
      - "8081:8081"  # Metrics
    depends_on:
      migrate:
        condition: service_completed_successfully
    command: ["/app/server"]

volumes:
  postgres_data:
